### ISSUE TITLE
How to access secrets in multipath under vault kv?

### ISSUE THREAD

**Issue by kouata** [gocd/gocd-vault-secret-plugin#114]
Hello, I got this tree structure in my vault:
kv/app1/dev/bdd_secret/
kv/app1/prod/app_secret/

kv/app2/dev/bdd_secret/
kv/app2/prod/app_secret/

How can I get secret from app1 or app2 tree according the environnement ? 
Like this:
VaultPath=kv 
var1={{SECRET:[testvault][app1/dev/bdd_secret/myuser1]}}
var2={{SECRET:[testvault][app1/prod/app_secret/myuser2]}}

I cannot a way to do this.
Thanks

**Comment by arvindsv** [comment]
Are you asking about dynamically creating the `{{SECRET:...` token? Meaning, using a separate variable, such as `VaultPath` in your example? I don't think that's possible. You could use multiple vault secret configurations, but it wouldn't be dynamic.

I don't know whether this will work (likely won't), but you can see if parameter expansion works inside secret tokens. Something like this:


Setup a parameter: `VaultPath=testvault1`

Try using a secret using that parameter: `var1={{SECRET:[#{VaultPath}][app1/dev/bdd_secret/myuser1]}}`

I'd be surprised if it works

**Comment by kouata** [comment]
I think it will not work because  VaultPath must be specified in the plugin config, and I think it's used when searching on vault. 

I managed to do this with a plugin but it hasn't approle auth method, just token (I didn't find a way to generate  a non-expiring token on vault).
The plugin doesn't ask VaultPath, just vault url et and a token.
I can access data this way:
var= {{SECRET:[vault-id][kv/data/my_app/my_en/app##data##my_password]}}
