### ISSUE TITLE
NameSpaces

### ISSUE THREAD

**Issue by idontwanttosignin** [gocd/gocd-vault-secret-plugin#3]
There does not seem to be any current support for namespaces. Is there a way to make this work with vault namespaces or any plans to implement it in the future?

**Comment by arvindsv** [comment]
From what I [understand of namespaces](https://www.vaultproject.io/docs/enterprise/namespaces/index.html#usage), can't you just prepend the namespace to the `VaultPath` configuration attribute?

**Comment by idontwanttosignin** [comment]
That doesn't quite work, at least for us, due to the driver passing in "data/" implicitly at the wrong location. According to their docs you can change this with a depth parameter. 
However I was able to successfully pass in a namespace to the driver in a forked version, and test it in our env. I'll submit that upstream once I clean it up a bit.

**Comment by maheshp** [comment]
Done as part of https://github.com/gocd/gocd-vault-secret-plugin/pull/4
