### ISSUE TITLE
No jar for latest release

### ISSUE THREAD

**Issue by brettcurtis** [gocd/gocd-vault-secret-plugin#6]
I'm going to try this out today, I noticed there is no jar for the latest release I will use this for now:

https://github.com/gocd/gocd-vault-secret-plugin/releases/download/v1.0.1-25/gocd-vault-secret-plugin-1.0.1-25.jar

**Comment by arvindsv** [comment]
@brettcurtis That's strange. I made a new commit just changing the case of a file, and the pipeline ran to release 1.1.0-31: https://github.com/gocd/gocd-vault-secret-plugin/releases/tag/v1.1.0-31 ... which does have the JAR.

I've marked 1.1.0-30 as pre-release. Thank you for bringing this up. I'll close this issue now.
